# Generated by Django 6.0.5 on 2026-06-01 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='ninjas',
        ),
        migrations.AddField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='app1.dojo'),
            preserve_default=False,
        ),
    ]
